/**
 * PROMPT C · Executive summary report assembly
 * Model: claude-sonnet-4-5
 * Version: v1.0.0 · April 23, 2026
 *
 * Purpose: After all themes are synthesized and citations verified, produce
 * the final markdown report the user will see and share.
 *
 * Edit rules: same as Prompts A and B.
 */

export const PROMPT_C_VERSION = "v1.0.0" as const;

export const PROMPT_C_SYSTEM = `\
You are producing an executive synthesis report from customer interviews. You are \
given a ranked list of themes already synthesized. Write a markdown report following \
the EXACT structure below.

# Customer Synthesis Report
*{N} interviews · Generated by Verbatim*

## What you should build next
[2-3 sentences. The single most actionable recommendation based on severity × frequency. \
No hedging. Pick one thing.]

## Top themes
[Render each theme as an H3. Preserve the title. Then: the description. Then: three \
bullet quotes, each formatted as:
> "<verbatim quote>" — {participant label}  \`[▶ chunk_id]\`
The \`[▶ chunk_id]\` is a placeholder the UI will turn into a playable audio button. \
Do not alter it.]

## Contradictions to investigate
[Any themes with contradiction_flag=true, each listed as a one-line summary. If none, \
write "None surfaced in this set of interviews."]

## What we didn't hear
[Topics you would have expected to surface in this customer segment but didn't. 2-3 \
specific bullets. Be concrete — "no one mentioned pricing" is better than "pricing \
was absent from discussion."]

Rules:
- Do not fabricate quotes. Every citation must reference a real chunk_id from the input.
- Keep total length under 1500 words.
- Voice: senior PM, not researcher. Crisp. Decision-oriented. No "users may feel that…"
- Do not add sections beyond the four above.`;

export function buildPromptCUserMessage(
  interviewCount: number,
  rankedThemes: ReadonlyArray<{
    title: string;
    description: string;
    severity: number;
    frequency: number;
    contradiction_flag: boolean;
    recommendation: "build_now" | "investigate" | "monitor" | "ignore";
    citations: ReadonlyArray<{
      chunk_id: string;
      verbatim_quote: string;
      participant_label: string | null;
    }>;
  }>,
): string {
  const themesXml = rankedThemes
    .map(
      (t, i) => `<theme rank="${i + 1}">
  <title>${t.title}</title>
  <description>${t.description}</description>
  <severity>${t.severity}</severity>
  <frequency>${t.frequency}</frequency>
  <contradiction>${t.contradiction_flag}</contradiction>
  <recommendation>${t.recommendation}</recommendation>
  <citations>
${t.citations
  .map(
    (c) =>
      `    <quote chunk_id="${c.chunk_id}" participant="${c.participant_label ?? "unknown"}">${c.verbatim_quote}</quote>`,
  )
  .join("\n")}
  </citations>
</theme>`,
    )
    .join("\n\n");

  return `N = ${interviewCount} interviews.\n\nRanked themes:\n\n${themesXml}\n\nProduce the markdown report now.`;
}
